[project]
name = "framework-mcp"
version = "0.1.0"
dependencies = [
    "fastapi==0.112.2",
    "uvicorn==0.30.5",
    "websockets==12.0",
    "pydantic==2.8.2"
]
[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
